import "../globals.css";
import React from "react";
import { dir } from "i18next";
import { TranslationsProvider } from "../../i18n";
import i18nConfig from "../../i18n.config";

export const metadata = {
  title: "Fixawy",
  description: "Generated by create-nx-workspace",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <TranslationsProvider locale={locale}>
      <html lang={locale} dir={dir(locale)}>
        <body>{children}</body>
      </html>
    </TranslationsProvider>
  );
}
